#include <string>
#include <exception>
#include <iostream>
#include <stdlib.h>

class Ball : public std::exception
{

};

class P
{
public:
	P* target;
	std::string name;
	int counter;

	P (P* target, std::string name)
	{
		this->target = target;
		this->name = name;
		counter = 0;
	}

	void aim (Ball* ball)
	{
		try
		{
			counter++;
			std::cout << name << " throws" << std::endl;
			throw ball;
		}
		catch (Ball* b)
		{
			if (counter > 5)
				exit(0);
			std::cout << target->name << " catches" << std::endl;
			target->aim(b);
		}
	}

};

int main()
{
	P* parent = new P(0, "Parent");
	P* child = new P(parent, "Child");
	parent->target = parent;//child;
	parent->aim(new Ball());
}
